/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication14;

import java.util.Scanner;

/**
 *
 * @author STIVEN
 */
import java.util.Scanner;
public class JavaApplication14 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
         Scanner objeto=new Scanner (System.in);

    System.out.println("Estudio experimental y predicción de rendimiento "
            + "y emisión en un motor SI que utiliza combustible alternativo "
            + "con red neuronal artificial");


    System.out.println("Ingrese el objeto Clase padre");
    String objeto1=objeto.nextLine();


    System.out.println(" \nAtributo 1");
    String atributo1=objeto.nextLine();

    System.out.println(" Atributo 2");
   String atributo2=objeto.nextLine();

    System.out.println(" Atributo 3");
    String atributo3=objeto.nextLine();

    System.out.println("\nServicio 1");
    String servicio1=objeto.nextLine();

    System.out.println(" Servicio 2");
    String servicio2=objeto.nextLine();

    System.out.println(" Servicio 3");
    String servicio3=objeto.nextLine();

    System.out.println("\nIngrese el objeto Clase hijo 1");
    String clase1=objeto.nextLine();
   System.out.println(" \nAtributo 1");
    String atributo21=objeto.nextLine();

    System.out.println(" Atributo 2");
    String atributo22=objeto.nextLine();

    System.out.println(" Atributo 3");
    String atributo23=objeto.nextLine();

    System.out.println(" \nServicio 1");
    String servicio21=objeto.nextLine();

    System.out.println(" Servicio 2");
   String servicio22=objeto.nextLine();

    System.out.println(" Servicio 3");
    String servicio23=objeto.nextLine();

    System.out.println("\nIngrese el objeto Clase hijo 2");
    String clase2=objeto.nextLine();

    System.out.println(" \nAtributo 1");
    String atributo31=objeto.nextLine();

    System.out.println(" Atributo 2");
    String atributo32=objeto.nextLine();

    System.out.println(" Atributo 3");
    String atributo33=objeto.nextLine();

    System.out.println("\nservicio 1");
    String servicio31=objeto.nextLine();

    System.out.println(" Servicio 2");
   String servicio32=objeto.nextLine();

    System.out.println(" Servicio 3");
    String servicio33=objeto.nextLine();
    }

}
